# Generated by Django 3.0.7 on 2020-07-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('usuario', models.CharField(max_length=100, unique=True, verbose_name='usuario')),
                ('telefono', models.CharField(max_length=50, verbose_name='telefono')),
                ('correo', models.EmailField(max_length=254, verbose_name='correo')),
                ('direccion', models.CharField(blank=True, max_length=500, null=True, verbose_name='domicilio')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='observaciones')),
            ],
        ),
    ]
