# Generated by Django 3.0.7 on 2020-07-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='modelo')),
                ('fecha_garantia', models.DateField(blank=True, null=True, verbose_name='fecha_garantia')),
                ('numero_serie', models.PositiveIntegerField(blank=True, null=True, verbose_name='numero_serie')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_equipo',
            fields=[
                ('id_estado_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_estado_equipo', models.DateField(blank=True, null=True, verbose_name='fecha_estado_equipo')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipo.Equipo')),
                ('tipo_etsado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.Tipo_estado_eq_rep')),
            ],
        ),
    ]
