# Generated by Django 3.0.7 on 2020-07-28 16:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tecnico', '0001_initial'),
        ('equipo', '0001_initial'),
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(blank=True, null=True, verbose_name='fecha_creacion')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='fecha_entrega')),
                ('pagado', models.BooleanField(default=False, verbose_name='pagado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='observaciones')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipo.Equipo')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tecnico.Tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_estado_incidencia',
            fields=[
                ('id_tipo_estado_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_incidencia',
            fields=[
                ('id_tipo_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Urgencia_incidencia',
            fields=[
                ('id_urgencia_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidencia.Incidencia')),
                ('tipo_urgencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.Tipo_urgencia')),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto_equipo',
            fields=[
                ('id_repuesto_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidencia.Incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='fecha_estado_incidencia')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidencia.Incidencia')),
            ],
        ),
        migrations.AddField(
            model_name='incidencia',
            name='tipo_incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidencia.Tipo_incidencia'),
        ),
        migrations.CreateModel(
            name='Estado_incidencia',
            fields=[
                ('id_estado_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_estado_incidencia', models.DateField(blank=True, null=True, verbose_name='fecha_estado_incidencia')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidencia.Incidencia')),
                ('tipo_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidencia.Tipo_estado_incidencia')),
            ],
        ),
    ]
