# Generated by Django 3.0.7 on 2020-07-24 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_incidencia',
            fields=[
                ('id_estado_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_estado_incidencia', models.DateField(blank=True, null=True, verbose_name='fecha_estado_incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(blank=True, null=True, verbose_name='fecha_creacion')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='fecha_entrega')),
                ('pagado', models.BooleanField(default=False, verbose_name='pagado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='observaciones')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto_equipo',
            fields=[
                ('id_repuesto_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_estado_incidencia',
            fields=[
                ('id_tipo_estado_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_incidencia',
            fields=[
                ('id_tipo_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Urgencia_incidencia',
            fields=[
                ('id_urgencia_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha')),
            ],
        ),
    ]
