# Generated by Django 3.0.7 on 2020-07-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_estado_eq_rep',
            fields=[
                ('id_tipo_estado_eq_rep', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre_estado')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_urgencia',
            fields=[
                ('id_tipo_urgencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre')),
            ],
        ),
    ]
