# Generated by Django 3.0.7 on 2020-07-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_estado_eq_rep',
            fields=[
                ('id_tipo_estado_eq_rep', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre_estado')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_urgencia',
            fields=[
                ('id_tipo_urgencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.Provincia')),
            ],
        ),
    ]
