# Generated by Django 3.0.7 on 2020-07-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id_consultorio', models.AutoField(primary_key=True, serialize=False)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True, verbose_name='barrio')),
                ('calle', models.CharField(blank=True, max_length=100, null=True, verbose_name='calle')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre')),
            ],
        ),
    ]
